version: '2.3'
services:
  issue_checker_service:
    image: issue_gpt
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVER=${SERVER}
        - USER_NAME=${USER_NAME}
        - PASSWORD=${PASSWORD}
        - DATABASE=${DATABASE}
        - CONNECTION_URL=${CONNECTION_URL}
    environment:
      - SERVER=${SERVER}
      - USER_NAME=${USER_NAME}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - CONNECTION_URL=${CONNECTION_URL}
    ports: 
      - 8000:8000
    depends_on:
      - redis

  redis:
      image: redis:4.0.6-alpine
      ports:
        - "6379:6379"
      volumes:
          - ./redis:/redis